---
language: python
cache: pip
python:
- "3.7"

env:
  global:
  - APP_DIR: aiidalab-template

before_install:
- pip install -U wheel setuptools

install:
- pip install cookiecutter pre-commit
- cookiecutter --no-input .
- cd ${APP_DIR}
- pip install -r requirements.txt

script:
- >
  git init;
  git add -A;
  pre-commit install;
  pre-commit run --all-files || ( git status --short ; git diff ; exit 1 );
